# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 065a301fbe8d372336611dfa55ef73a43c88c1cb34deb9483245b84ebaca7f03a2eff88e12b4dbdaf7198c6b90b8a70111b879799e2a3b1914a56a36e7b9237c

test:
  secret_key_base: 0c1dd69c85d647a92f2c230838b29883b6f480b93cbebcaaa2e92b35b2cafd9967b25786244285e0210c4c4f2f116c905f3c35b40fba3ee1a7bf0c03e7998538

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
